all:
	TEXINPUTS="../Cmd:" xelatex martin_tourneboeuf_cv_english.tex

full:
	TEXINPUTS="../Cmd:" xelatex martin_tourneboeuf_cv_english_full.tex

french:
	TEXINPUTS="../Cmd:" xelatex martin_tourneboeuf_cv_french.tex

spanish:
	TEXINPUTS="../Cmd:" xelatex martin_tourneboeuf_cv_spanish.tex
